services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: express_form_cod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - express_form_cod_pg:/var/lib/postgresql/data

volumes:
  express_form_cod_pg:
