# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "503c6d04087a5e0fbbf1dc0c446c3462"
application_url = "https://expressformcod.com/"
embedded = true
name = "express-form-cod"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_draft_orders,write_draft_orders,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://expressformcod.com/auth/callback",
  "https://expressformcod.com/auth/shopify/callback",
  "https://expressformcod.com/api/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://expressformcod.com/"
subpath = "express-cod"
prefix = "apps"
